// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT3jxOWYY0CoxtMcA0KVguEtd7mV9xtY4',
    appId: '1:881157721637:android:4ac5ab05bb0ceedeec39cc',
    messagingSenderId: '881157721637',
    projectId: 'exnay-a6d8d',
    databaseURL: 'https://exnay-a6d8d-default-rtdb.firebaseio.com',
    storageBucket: 'exnay-a6d8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn1bx_Q1SoxGyICYaIWeWgY1UJ88cZyXA',
    appId: '1:881157721637:ios:4b01f6edc42ff964ec39cc',
    messagingSenderId: '881157721637',
    projectId: 'exnay-a6d8d',
    databaseURL: 'https://exnay-a6d8d-default-rtdb.firebaseio.com',
    storageBucket: 'exnay-a6d8d.firebasestorage.app',
    androidClientId: '881157721637-8kdhnu5vpvts77jua3htce8vl1dai22a.apps.googleusercontent.com',
    iosClientId: '881157721637-b35bsog4sm2ao5gpoivsstffiq5d06v8.apps.googleusercontent.com',
    iosBundleId: 'app.ngawinapp.ios',
  );
}